# 1. Server Configuration
server.port=8080
spring.application.name=transaction-engine

# 2. Database Connection (CRITICAL: Name it 'sentineldb')
spring.datasource.url=jdbc:h2:mem:sentineldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# 3. JPA / Hibernate Settings
# 'update' will auto-create your TRANSACTION_RECORD table based on your @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. H2 Console Settings (The UI to see your data)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# This allows you to access the console without Spring Security blocking it (if added later)
spring.h2.console.settings.web-allow-others=true

# 5. Feign Client Configuration (Pointing to the Risk Engine)
# Ensure this matches the port your Risk Engine is running on
risk-service.url=http://localhost:8081

spring.cloud.openfeign.circuitbreaker.enabled=true
feign.circuitbreaker.enabled=true

# Add these for better debugging
logging.level.io.github.resilience4j=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG

@EnableFeignClients(basePackages = "com.sentinel.transaction.client")